name: luna_fashion
description: Luna Fashion es una app eCommerce de ropa
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_native_splash: ^2.1.2+1 #native splash
  flutter_launcher_icons: ^0.9.2 #native icon app
  flutter_riverpod: ^1.0.3 #state
  #firebase
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  firebase_storage: ^10.2.10
  firebase_analytics: ^9.1.3
  firebase_crashlytics: ^2.6.0
  cloud_firestore: ^3.1.11

  logger: ^1.1.0 #logs
  another_flushbar: ^1.10.28 #toasts

  lottie: ^1.2.2 #images with anim
  flutter_svg: ^1.0.3 #images svg
  image_picker: ^0.8.5 #pick images
  url_launcher: ^6.0.20 #redirect webs
  flutter_slidable: ^1.2.0 #slidable items

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lotties/

flutter_native_splash:
  image: assets/images/splash.png
  color: "#ffffff"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_launch.png"

flutter_intl:
  enabled: true
  main_locale: es
  arb_dir: lib/src/shared/presentation/l10n
  output_dir: lib/src/shared/presentation/l10n/generated
